package main

import (
	"net/http/httptest"
	"testing"
	"time"
)

func TestSessionStore_SaveAndGet(t *testing.T) {
	store := NewSessionStore()
	
	r := httptest.NewRequest("GET", "/?session=test123", nil)
	session := &Session{
		Token:     "test-token",
		UserInfo:  UserInfoResponse{Sub: "test-user"},
		ExpiresAt: time.Now().Add(time.Hour),
	}
	
	store.Save(r, session)
	
	retrieved, exists := store.Get(r)
	if !exists {
		t.Fatal("Session should exist")
	}
	
	if retrieved.Token != session.Token {
		t.Errorf("Token mismatch: %s != %s", retrieved.Token, session.Token)
	}
	
	if retrieved.UserInfo.Sub != session.UserInfo.Sub {
		t.Error("UserInfo mismatch")
	}
}

func TestSessionStore_GetWithMissingSession(t *testing.T) {
	store := NewSessionStore()
	
	r := httptest.NewRequest("GET", "/?session=nonexistent", nil)
	_, exists := store.Get(r)
	
	if exists {
		t.Error("Session should not exist")
	}
}

func TestSessionStore_SaveWithAutoGeneratedSession(t *testing.T) {
	store := NewSessionStore()

	r := httptest.NewRequest("GET", "/?session=auto", nil)
	session := &Session{
		Token:     "test-token",
		UserInfo:  UserInfoResponse{Sub: "test-user"},
		ExpiresAt: time.Now().Add(time.Hour),
	}

	store.Save(r, session)

	// Get should work with the same request
	retrieved, exists := store.Get(r)
	if !exists {
		t.Fatal("Session should exist")
	}

	if retrieved.Token != session.Token {
		t.Error("Token should match")
	}
}

func TestSessionStore_CleanupExpired(t *testing.T) {
	store := NewSessionStore()
	
	r1 := httptest.NewRequest("GET", "/?session=active", nil)
	r2 := httptest.NewRequest("GET", "/?session=expired", nil)
	
	session1 := &Session{
		Token:     "token1",
		UserInfo:  UserInfoResponse{Sub: "user1"},
		ExpiresAt: time.Now().Add(time.Hour),
	}
	session2 := &Session{
		Token:     "token2",
		UserInfo:  UserInfoResponse{Sub: "user2"},
		ExpiresAt: time.Now().Add(-time.Hour),
	}
	
	store.Save(r1, session1)
	store.Save(r2, session2)
	
	store.CleanupExpired()
	
	_, exists1 := store.Get(r1)
	_, exists2 := store.Get(r2)
	
	if !exists1 {
		t.Error("Active session should exist")
	}
	
	if exists2 {
		t.Error("Expired session should be removed")
	}
}
